name: "Check Formatting"
description: "Check Formatting for our application"

inputs:
  # https://stackoverflow.com/questions/70098241/using-secrets-in-composite-actions-github
  formatting-tool:
    description: The type of formatting tool, either dotnet-format or csharpier
    default: csharpier

# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-composite-actions
runs:
  using: "composite"
  steps:
    - name: Restore .Net Tools
      shell: bash
      run: |
        dotnet tool restore

    # https://dev.to/felipetofoli/code-formatting-for-c-projects-dotnet-format-github-actions-54p8
    - name: dotnet Formatting Check
      shell: bash
      if: (inputs.formatting-tool == 'dotnet-format')
      run: |
        dotnet format '.\' --folder --check --verbosity diagnostic

    # https://csharpier.com/docs/ContinuousIntegration
    - name: Charpire Formatting Check
      if: (inputs.formatting-tool == 'csharpier')
      shell: bash
      run: |
         dotnet csharpier --check .
