# # https://www.richard-banks.org/2018/07/debugging-core-in-docker.html
# https://docs.docker.com/compose/reference/#use--f-to-specify-name-and-path-of-one-or-more-compose-files
# https://docs.docker.com/compose/extends/
# if you have both 'docker-compose.services.yaml' and 'docker-compose.services.dev.yml' in the same directory, the latter will override the former. If you have multiple override files, you can specify them in order subsequently

# To build and debug the app on prod machine --> docker-compose -f docker-compose.services.yaml -f docker-compose.override.yaml build
# To start and debug the app on prod machine --> docker-compose -f docker-compose.services.yaml -f docker-compose.override.yaml up -d

version: "3.8"
services:
  # gateway:
  # # https://nickjanetakis.com/blog/docker-tip-57-using-build-and-image-in-the-same-docker-compose-servicemage
  # # https://github.com/opencontainers/.github/blob/master/docs/docs/introduction/digests.md
  # image: ${REGISTRY}/${PROJECT_NAME}/gateway-service:${TAG}
  # container_name: gateway-{TAG}
  # # https://docs.docker.com/compose/compose-file/compose-file-v3/#restart
  # restart: on-failure
  # ports:
  #   - ${GATEWAY_PORT}:80
  # # https://docs.docker.com/compose/environment-variables/set-environment-variables/
  # # https://docs.docker.com/compose/environment-variables/env-file/
  # environment:
  #   - ASPNETCORE_ENVIRONMENT=docker
  # networks:
  #   - ecommerce

  catalogs:
    # https://nickjanetakis.com/blog/docker-tip-57-using-build-and-image-in-the-same-docker-compose-service
    # https://github.com/opencontainers/.github/blob/master/docs/docs/introduction/digests.md
    image: ${REGISTRY}/${PROJECT_NAME}/catalogs-service:${TAG}
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#restart
    restart: on-failure
    container_name: catalogs-{TAG}
    # restart: unless-stopped
    ports:
      - ${CATALOGS_SVC_PORT}:80
    # https://docs.docker.com/compose/environment-variables/set-environment-variables/
    # https://docs.docker.com/compose/environment-variables/env-file/
    # .env file will resolved implicitly
    env_file:
      - ./catalogs.env
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    networks:
      - ecommerce

  identity:
    # https://nickjanetakis.com/blog/docker-tip-57-using-build-and-image-in-the-same-docker-compose-service
    # https://github.com/opencontainers/.github/blob/master/docs/docs/introduction/digests.md
    image: ${REGISTRY}/${PROJECT_NAME}/identity-service:${TAG}
    container_name: identity-{TAG}
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#restart
    restart: on-failure
    ports:
      - ${IDENTITY_SVC_PORT}:80
    # https://docs.docker.com/compose/environment-variables/set-environment-variables/
    # https://docs.docker.com/compose/environment-variables/env-file/
    # .env file will resolved implicitly
    env_file:
      - ./identity.env
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    networks:
      - ecommerce

  customers:
    # https://nickjanetakis.com/blog/docker-tip-57-using-build-and-image-in-the-same-docker-compose-service
    # https://github.com/opencontainers/.github/blob/master/docs/docs/introduction/digests.md
    image: ${REGISTRY}/${PROJECT_NAME}/customers-service:${TAG}
    container_name: customers-{TAG}
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#restart
    restart: on-failure
    ports:
      - ${CUSTOMERS_SVC_PORT}:80
    # https://docs.docker.com/compose/environment-variables/set-environment-variables/
    # https://docs.docker.com/compose/environment-variables/env-file/
    # .env file will resolved implicitly
    env_file:
      - ./customers.env
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    networks:
      - ecommerce

# https://docs.docker.com/compose/networking/
# https://docs.docker.com/engine/reference/commandline/network_create/
# https://docs.docker.com/compose/compose-file/#networks-top-level-element
# https://stackoverflow.com/questions/38088279/communication-between-multiple-docker-compose-projects
# We could use also a predefined network and connect to that predefined network with specifying the 'name' of existing network and set 'external' attribute to true
# When we run docker-compose up, Docker Compose will check if the 'ecommerce' network already exists. If it does not exist, it will create the 'ecommerce' network. If it exists, it will use the existing 'ecommerce' network. problem is that if we do a docker-compose down this network will delete and other docker-compose that use same network will fail because network deleted so its better we use `external` keyword for using a predefined network
networks:
  ecommerce:
    name: ecommerce
    driver: bridge
    # we can use the network that will create by infrastructure docker-compose file and we use that network here by specifying existing network 'name' and set 'external' attribute to 'true' (because we want to use a network outside of our docker-compose) or we can create a `ecommerce` network manually by `docker network create -d bridge ecommerce` and use this network as external network for all docker-compose files
    external: true
