name: Reusable Release Workflow

on:
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_call
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputs
  # https://stackoverflow.com/questions/73702333/github-actions-reuse-outputs-from-other-reusable-workflows
  # https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-outputs-from-a-reusable-workflow
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputsinput_idtype
  # https://docs.github.com/en/actions/using-workflows/reusing-workflows
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      release-version:
        description: "Version"
        value: ${{ jobs.release.outputs.release-version }}
jobs:

  release:
    name: Release
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idpermissions
    # https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-ghcrio
    ## https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository
    ## https://docs.github.com/en/actions/using-workflows/reusing-workflows
    # The GITHUB_TOKEN permissions passed from the caller workflow can be only downgraded in called workflow
    permissions:
      contents: write # to be able to publish a GitHub release and tags

    # Map the job outputs to step outputs
    outputs:
      release-version: ${{ steps.release-note-step.outputs.application-version }}

    steps:

      # https://docs.github.com/en/actions/learn-github-actions/variables#using-contexts-to-access-variable-values
      - name: Job Info
        run: |
          echo "job name is: $GITHUB_JOB"
          echo workspace is: ${{ github.workspace }}
          echo "is workflow_dispatch event? ${{ github.event_name == 'workflow_dispatch' }}"
          echo "is push event? ${{ github.event_name == 'push' }}"
          echo "is pull request event? ${{ github.event_name == 'pull_request' }}"
          echo "pull_request.head.ref is: ${{ github.event.pull_request.head.ref }}"
          echo "github.ref_name is: ${{ github.ref_name }}"
          echo "github.ref is: ${{ github.ref }}"
          echo "github.head_ref is: ${{ github.head_ref }}"

      - name: Call Composite Action checkout
        uses: ./.github/actions/checkout-code
        id: checkout-step

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Call Composite Action semantic-release-note
        uses: ./.github/actions/semantic-release-note
        id: release-note-step
        with:
          token:  ${{ secrets.GITHUB_TOKEN }}

  release-info:
    name: Release Info
    runs-on: ubuntu-latest
    needs: [ release ]
    steps:
      - name: Release Info
        run: |
          echo "release version is: ${{ needs.release.outputs.release-version }}"

